//
//
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const GET_COLLECTION = 'GET_COLLECTION';
export const GET_COLLECTION_FAILED = 'GET_COLLECTION_FAILED';
export const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS';
